---
resource_types:
- name: tile
  type: docker-image
  source:
    repository: solace/solace-product-download
    tag: latest

resources:
- name: solace-tile
  type: tile
  source:
    username: {{my_solace_username}}
    password: {{my_solace_password}}
    filepath: "/products/2.3GA/PCF/Current/2.3.2/solace-pubsub-2.3.2-enterprise.pivotal"
    accept_terms: true
jobs:
- name: demo-resource
  plan:
  - get: solace-tile
  - task: show-tile # shows the tile downloaded by solace-tile get above
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: solace/solace-product-download
          tag: latest
      inputs:
      - name: solace-tile
      run:
        path: bash
        args:
        - -exc
        - |
          echo "Running demo pipeline, this task displays the resulting files"
          ls
          ls solace-tile
